### ISSUE TITLE
Cannot use interpolation in backend configuration (Terraform shared state)

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-it/static-sites-aws#6]
We cannot use interpolation in the S3 backend configuration. We'll need to find another approach when specifying the `key` for the shared state. We can provide it manually for now with the intention of improving it in the future.

```
Initializing the backend...
Error loading backend config: 1 error(s) occurred:

* terraform.backend: configuration cannot contain interpolations

The backend configuration is loaded by Terraform extremely early, before
the core of Terraform can be initialized. This is necessary because the backend
dictates the behavior of that core. The core is what handles interpolation
processing. Because of this, interpolations cannot be used in backend
configuration.

If you'd like to parameterize backend configuration, we recommend using
partial configuration with the "-backend-config" flag to "terraform init".
```

**Comment by danielhartnell** [comment]
This is fixed in: https://github.com/mozilla-it/static-sites-aws/commit/6decaf1b180e1b8cdb4d78cd0afa53f6831a63c6

I would like to leave this issue open so we can discuss potential solutions. I think we're comfortable hard coding the path (the `key`) for now but it would be nice to find a more elegant solution. Something less vulnerable to user error would be wonderful.

**Comment by limed** [comment]
An option to do this is to self discover certain aspect of the backend, this means you will have to standardize the bucket name for the state something like `static-sites-<account number>` or `static-sites-<hash>` and the key would be something like `terraform/<site-name>`

And you would have to write a wrapper around it to call terraform

```
terraform init -backend-config="key=blah" -backend-config="bucket=blah"
```
